config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-sapphire-magpie.sh
        container: qc.acc_ugly-salmon-terrier
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-apricot-jackal.sh
        container: qc.doc_crabby-rust-javanese
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-brown-badger.sh
        container: qc.doc_flimsy-cream-giraffe
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-linen-mastiff.sh
        container: qc.doc_trippy-mustard-capuchin
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-razzmatazz-stingray.sh
        container: qc.doc_lovely-pink-olm
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-harlequin-squirt.sh
        container: qc.lic_slaphappy-cinnabar-beaver
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-peach-tortoise.sh
        container: qc.met_homely-brass-wolverine
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-grey-warthog.sh
        container: qc.sec_lousy-maroon-toucan
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-firebrick-frise.sh
        container: qc.sty_sleazy-rust-goose
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-lilac-bulldog.sh
        container: qc.sty_sleazy-sepia-devil
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-firebrick-chimpanzee.sh
        container: qc.sty_sunny-lilac-quoll
  QC.Uni:
    repos:
      github.com/grycap/im tox:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-teal-crocodile.sh
        container: qc.uni_woozy-peach-koala
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-sapphire-falcon.sh
        container: qc.ver_snazzy-taupe-macaque
timeout: 5400
