config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-jade-dollar.sh
        container: qc.acc_queasy-gold-shark
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-champagne-panda.sh
        container: qc.doc_whiny-persimmon-indri
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-yellow-eagle.sh
        container: qc.doc_queasy-pear-collie
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-charcoal-sparrow.sh
        container: qc.doc_zippy-goldenrod-skunk
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-orchid-molly.sh
        container: qc.doc_wiggy-bistre-opossum
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-brass-rhinoceros.sh
        container: qc.lic_cheeky-dandelion-dormouse
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-wisteria-maltese.sh
        container: qc.met_bumpy-cardinal-iguana
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-mauve-mammoth.sh
        container: qc.sec_hasty-ecru-goose
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.randy-thistle-booby.sh
        container: qc.sty_stinky-vermilion-moth
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-mauve-catfish.sh
        container: qc.sty_beady-saffron-bonobo
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-cerulean-quokka.sh
        container: qc.sty_goopy-sangria-hummingbird
  QC.Uni:
    repos:
      github.com/grycap/im tox:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-bistre-insect.sh
        container: qc.uni_flabby-goldenrod-tamarin
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-lilac-eel.sh
        container: qc.ver_pokey-blue-kudu
timeout: 5400
