config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-platinum-mist.sh
        container: qc.acc_pasty-wheat-loon
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-beige-dog.sh
        container: qc.doc_pasty-firebrick-buffalo
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-lavender-fox.sh
        container: qc.doc_randy-apricot-mule
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.homely-corn-cat.sh
        container: qc.doc_cozy-fuchsia-termite
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-indigo-wildebeest.sh
        container: qc.doc_snoopy-cobalt-cat
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-grey-penguin.sh
        container: qc.lic_stealthy-tan-barb
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-copper-ragdoll.sh
        container: qc.met_smelly-rose-lionfish
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-myrtle-salamander.sh
        container: qc.sec_lanky-malachite-penguin
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-eggplant-moose.sh
        container: qc.sty_sunny-auburn-mau
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-harlequin-centipede.sh
        container: qc.sty_wimpy-bistre-stoat
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-coral-beagle.sh
        container: qc.sty_whiny-black-dollar
  QC.Uni:
    repos:
      github.com/grycap/im pytest:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-razzmatazz-falcon.sh
        container: qc.uni_wimpy-cinnamon-toad
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-teal-zonkey.sh
        container: qc.ver_lanky-tomato-mastiff
timeout: 5400
