config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.plum_reflective_grizzly.sh
        container: qc.acc_gray_intuitive_skunk
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.mauve_insightful_tiger.sh
        container: qc.doc_carmine_dizzy_snail
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.pansy_polite_sloth.sh
        container: qc.doc_zinnia_quirky_hare
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ultramarine_organized_panda.sh
        container: qc.doc_nutmeg_tactful_eel
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.forest_dramatic_grasshopper.sh
        container: qc.doc_rust_generous_elephant
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pumpkin_trustworthy_pelican.sh
        container: qc.lic_orange_reflective_snail
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.papaya_authentic_whale.sh
        container: qc.met_crimson_innocent_eagle
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.puce_savvy_gull.sh
        container: qc.sec_prussian_mindful_porcupine
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lemon_agile_antelope.sh
        container: qc.sty_chartreuse_loving_goat
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.carmine_worried_quoll.sh
        container: qc.sty_mint_confident_meerkat
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sepia_tranquil_mongoose.sh
        container: qc.sty_orange_sociable_camel
  QC.Uni:
    repos:
      github.com/grycap/im pytest:
        commands:
        - /usr/bin/env sh .sqa/script.mahogany_attentive_cormorant.sh
        container: qc.uni_marigold_agile_crocodile
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cosmos_devoted_cheetah.sh
        container: qc.ver_lavender_fearless_wildcat
timeout: 5400
