config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-bronze-loon.sh
        container: qc.acc_leaky-ecru-zebra
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-razzmatazz-discus.sh
        container: qc.doc_ready-green-burmese
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-alizarin-kiwi.sh
        container: qc.doc_whiny-carmine-bongo
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-magenta-abyssinian.sh
        container: qc.doc_stinky-plum-deer
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-wisteria-caracal.sh
        container: qc.doc_squeaky-khaki-cockroach
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.beady-corn-salamander.sh
        container: qc.lic_stealthy-taupe-dragon
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-buff-gibbon.sh
        container: qc.met_chewy-ecru-turtle
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-tomato-panda.sh
        container: qc.sec_seedy-taupe-affenpinscher
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-pear-horse.sh
        container: qc.sty_jumpy-olive-zorse
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-copper-binturong.sh
        container: qc.sty_sunny-green-quetzal
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-heliotrope-dragonfly.sh
        container: qc.sty_wiggy-smalt-grasshopper
  QC.Uni:
    repos:
      github.com/grycap/im pytest:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-vermilion-kiwi.sh
        container: qc.uni_shabby-tan-macaw
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-dandelion-eel.sh
        container: qc.ver_sickly-charcoal-fousek
timeout: 5400
