config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-magnolia-sheepdog.sh
        container: qc.acc_nerdy-sepia-sponge
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-vermilion-pig.sh
        container: qc.doc_shaky-sapphire-dane
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-fuchsia-spider.sh
        container: qc.doc_stealthy-grey-newt
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-sangria-buffalo.sh
        container: qc.doc_chummy-aquamarine-grasshopper
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-chocolate-echidna.sh
        container: qc.doc_silly-sepia-crane
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-orchid-whale.sh
        container: qc.lic_squirrely-emerald-iguana
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-sapphire-donkey.sh
        container: qc.met_crappy-cobalt-argentino
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-cyan-owl.sh
        container: qc.sec_gamy-ecru-dog
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-bistre-toucan.sh
        container: qc.sty_snippy-burgundy-meerkat
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-cinnabar-robin.sh
        container: qc.sty_muzzy-emerald-oyster
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-puce-snail.sh
        container: qc.sty_homey-heliotrope-dodo
  QC.Uni:
    repos:
      github.com/grycap/im pytest:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-beige-slug.sh
        container: qc.uni_craggy-olive-sparrow
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-ivory-foxhound.sh
        container: qc.ver_hazy-orange-booby
timeout: 5400
