config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-cinnamon-balinese.sh
        container: qc.acc_cheeky-celadon-cuttlefish
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-burgundy-paradise.sh
        container: qc.doc_freaky-orange-dhole
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-gold-antelope.sh
        container: qc.doc_lanky-seashell-oyster
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-peach-sheepdog.sh
        container: qc.doc_flabby-malachite-ibis
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-viridian-gopher.sh
        container: qc.doc_stuffy-sepia-catfish
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-lilac-crab.sh
        container: qc.lic_shabby-tomato-hornet
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-taupe-armadillo.sh
        container: qc.met_stealthy-orange-woodlouse
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-purple-eagle.sh
        container: qc.sec_pretty-gamboge-duck
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.homely-rose-owl.sh
        container: qc.sty_tacky-ochre-sheepdog
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-blue-giraffe.sh
        container: qc.sty_bluesy-tangerine-ray
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-champagne-antelope.sh
        container: qc.sty_shabby-heliotrope-argentino
  QC.Uni:
    repos:
      github.com/grycap/im pytest:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-orange-angelfish.sh
        container: qc.uni_silly-brass-armadillo
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-aqua-tuatara.sh
        container: qc.ver_wheezy-tan-quail
timeout: 5400
